In [1]:
import numpy as np
import pandas as pd
import torch
from sklearn.preprocessing import StandardScaler
from sklearn.model_selection import train_test_split
from sklearn.preprocessing import LabelEncoder

In [2]:
df =pd.read_csv('https://raw.githubusercontent.com/gscdit/Breast-Cancer-Detection/refs/heads/master/data.csv')

In [3]:
df

,id,diagnosis,radius_mean,texture_mean,perimeter_mean,area_mean,smoothness_mean,compactness_mean,concavity_mean,concave points_mean,...,texture_worst,perimeter_worst,area_worst,smoothness_worst,compactness_worst,concavity_worst,concave points_worst,symmetry_worst,fractal_dimension_worst,Unnamed: 32
0,842302,M,17.99,10.38,122.80,1001.0,0.11840,0.27760,0.30010,0.14710,...,17.33,184.60,2019.0,0.16220,0.66560,0.7119,0.2654,0.4601,0.11890,NaN
1,842517,M,20.57,17.77,132.90,1326.0,0.08474,0.07864,0.08690,0.07017,...,23.41,158.80,1956.0,0.12380,0.18660,0.2416,0.1860,0.2750,0.08902,NaN
2,84300903,M,19.69,21.25,130.00,1203.0,0.10960,0.15990,0.19740,0.12790,...,25.53,152.50,1709.0,0.14440,0.42450,0.4504,0.2430,0.3613,0.08758,NaN
3,84348301,M,11.42,20.38,77.58,386.1,0.14250,0.28390,0.24140,0.10520,...,26.50,98.87,567.7,0.20980,0.86630,0.6869,0.2575,0.6638,0.17300,NaN
4,84358402,M,20.29,14.34,135.10,1297.0,0.10030,0.13280,0.19800,0.10430,...,16.67,152.20,1575.0,0.13740,0.20500,0.4000,0.1625,0.2364,0.07678,NaN
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
564,926424,M,21.56,22.39,142.00,1479.0,0.11100,0.11590,0.24390,0.13890,...,26.40,166.10,2027.0,0.14100,0.21130,0.4107,0.2216,0.2060,0.07115,NaN
565,926682,M,20.13,28.25,131.20,1261.0,0.09780,0.10340,0.14400,0.09791,...,38.25,155.00,1731.0,0.11660,0.19220,0.3215,0.1628,0.2572,0.06637,NaN
566,926954,M,16.60,28.08,108.30,858.1,0.08455,0.10230,0.09251,0.05302,...,34.12,126.70,1124.0,0.11390,0.30940,0.3403,0.1418,0.2218,0.07820,NaN
567,927241,M,20.60,29.33,140.10,1265.0,0.11780,0.27700,0.35140,0.15200,...,39.42,184.60,1821.0,0.16500,0.86810,0.9387,0.2650,0.4087,0.12400,NaN
568,92751,B,7.76,24.54,47.92,181.0,0.05263,0.04362,0.00000,0.00000,...,30.37,59.16,268.6,0.08996,0.06444,0.0000,0.0000,0.2871,0.07039,NaN

In [4]:
df.shape

(569, 33)

In [5]:
df.columns

Index(['id', 'diagnosis', 'radius_mean', 'texture_mean', 'perimeter_mean',
       'area_mean', 'smoothness_mean', 'compactness_mean', 'concavity_mean',
       'concave points_mean', 'symmetry_mean', 'fractal_dimension_mean',
       'radius_se', 'texture_se', 'perimeter_se', 'area_se', 'smoothness_se',
       'compactness_se', 'concavity_se', 'concave points_se', 'symmetry_se',
       'fractal_dimension_se', 'radius_worst', 'texture_worst',
       'perimeter_worst', 'area_worst', 'smoothness_worst',
       'compactness_worst', 'concavity_worst', 'concave points_worst',
       'symmetry_worst', 'fractal_dimension_worst', 'Unnamed: 32'],
      dtype='object')

In [6]:
df.drop(columns=['id','Unnamed: 32'],inplace=True)

In [7]:
df.shape

(569, 31)

TRAIN-TEST-SPLIT

In [8]:
x_train,x_test,y_train,y_test = train_test_split(df.drop(columns=['diagnosis']),df['diagnosis'],test_size=0.2,random_state=42)

In [9]:
#SCALING

In [10]:
scaler =StandardScaler()
x_train = scaler.fit_transform(x_train)
x_test = scaler.transform(x_test)

In [11]:
x_train

array([[-1.44075296, -0.43531947, -1.36208497, ...,  0.9320124 ,
         2.09724217,  1.88645014],
       [ 1.97409619,  1.73302577,  2.09167167, ...,  2.6989469 ,
         1.89116053,  2.49783848],
       [-1.39998202, -1.24962228, -1.34520926, ..., -0.97023893,
         0.59760192,  0.0578942 ],
       ...,
       [ 0.04880192, -0.55500086, -0.06512547, ..., -1.23903365,
        -0.70863864, -1.27145475],
       [-0.03896885,  0.10207345, -0.03137406, ...,  1.05001236,
         0.43432185,  1.21336207],
       [-0.54860557,  0.31327591, -0.60350155, ..., -0.61102866,
        -0.3345212 , -0.84628745]])

In [12]:
y_train

68     B
181    M
63     B
248    B
60     B
      ..
71     B
106    B
270    B
435    M
102    B
Name: diagnosis, Length: 455, dtype: object

In [13]:
lb =LabelEncoder()
y_train = lb.fit_transform(y_train)
y_test = lb.transform(y_test)

In [14]:
x_train_tensor =torch.from_numpy(x_train.astype(np.float32))
x_test_tensor =torch.from_numpy(x_test.astype(np.float32))
y_train_tensor =torch.from_numpy(y_train.astype(np.float32))
y_test_tensor =torch.from_numpy(y_test.astype(np.float32))

In [15]:
x_train_tensor.shape

torch.Size([455, 30])

In [16]:
from torch.utils.data import Dataset,DataLoader
class customdataset(Dataset):
    def __init__(self,x,y):
        self.x=x
        self.y=y
    def __len__(self):
        return len(self.x)
    def __getitem__(self,idx):
        return self.x[idx],self.y[idx]

In [17]:
train_dataset =customdataset(x_train_tensor,y_train_tensor)
test_dataset =customdataset(x_test_tensor,y_test_tensor)

In [18]:
train_loader =DataLoader(train_dataset,batch_size=32,shuffle=True)
test_loader =DataLoader(test_dataset,batch_size=32,shuffle=True)

#defining the model

In [19]:

import torch
import torch.nn as nn

class MysimpleNN(nn.Module):
    def __init__(self, num_features):
        super().__init__()

        self.linear = nn.Linear(num_features, 1)
        self.sigmoid = nn.Sigmoid()

    def forward(self, features):
        out = self.linear(features)
        out = self.sigmoid(out)
        return out



        return loss

In [20]:
loss_function =nn.BCELoss()

In [21]:
#important parameters
learning_rate =0.01
epochs=56

Training pipeline

In [22]:
model = MysimpleNN(x_train_tensor.shape[1])
optimizer =torch.optim.SGD(model.parameters(),lr=learning_rate)

for epoch in range(epochs):

    # Forward pass
    y_pred = model.forward(x_train_tensor)

    # Compute loss
    loss = loss_function(y_pred, y_train_tensor.view(-1,1))

    # Zero gradients
    optimizer.zero_grad()

    # Backward pass
    loss.backward()

    # Update parameters
    optimizer.step()


    print(f"Loss after epoch {epoch+1}: {loss.item():.4f}")

Loss after epoch 1: 0.6890
Loss after epoch 2: 0.6681
Loss after epoch 3: 0.6484
Loss after epoch 4: 0.6299
Loss after epoch 5: 0.6125
Loss after epoch 6: 0.5962
Loss after epoch 7: 0.5808
Loss after epoch 8: 0.5664
Loss after epoch 9: 0.5528
Loss after epoch 10: 0.5400
Loss after epoch 11: 0.5279
Loss after epoch 12: 0.5165
Loss after epoch 13: 0.5057
Loss after epoch 14: 0.4955
Loss after epoch 15: 0.4859
Loss after epoch 16: 0.4767
Loss after epoch 17: 0.4680
Loss after epoch 18: 0.4598
Loss after epoch 19: 0.4519
Loss after epoch 20: 0.4444
Loss after epoch 21: 0.4373
Loss after epoch 22: 0.4305
Loss after epoch 23: 0.4240
Loss after epoch 24: 0.4178
Loss after epoch 25: 0.4118
Loss after epoch 26: 0.4061
Loss after epoch 27: 0.4006
Loss after epoch 28: 0.3954
Loss after epoch 29: 0.3903
Loss after epoch 30: 0.3855
Loss after epoch 31: 0.3808
Loss after epoch 32: 0.3763
Loss after epoch 33: 0.3720
Loss after epoch 34: 0.3678
Loss after epoch 35: 0.3638
Loss after epoch 36: 0.3599
Loss after epoch 37: 0.3561
Loss after epoch 38: 0.3525
Loss after epoch 39: 0.3489
Loss after epoch 40: 0.3455
Loss after epoch 41: 0.3422
Loss after epoch 42: 0.3390
Loss after epoch 43: 0.3359
Loss after epoch 44: 0.3329
Loss after epoch 45: 0.3300
Loss after epoch 46: 0.3271
Loss after epoch 47: 0.3244
Loss after epoch 48: 0.3217
Loss after epoch 49: 0.3191
Loss after epoch 50: 0.3165
Loss after epoch 51: 0.3140
Loss after epoch 52: 0.3116
Loss after epoch 53: 0.3093
Loss after epoch 54: 0.3070
Loss after epoch 55: 0.3048
Loss after epoch 56: 0.3026

In [23]:
model.linear.weight

Parameter containing:
tensor([[ 0.1371,  0.1636,  0.0727,  0.1719,  0.2335,  0.1032,  0.2261, -0.0448,
          0.1207, -0.1591,  0.1257, -0.1397,  0.1208, -0.0943, -0.0583, -0.0436,
         -0.0603,  0.1583, -0.0043, -0.0188,  0.1575,  0.2051, -0.0682,  0.2253,
          0.1126,  0.0121,  0.0181,  0.1272,  0.0216,  0.0108]],
       requires_grad=True)

In [24]:
model.linear.bias

Parameter containing:
tensor([-0.1709], requires_grad=True)

#evaluation

In [25]:
model.eval()
accuracy_list =[]
with torch.no_grad():
    for x_test_batch,y_test_batch in test_loader:
        y_test_pred =model(x_test_batch)
        y_test_pred =(y_test_pred>0.5).float()
        accuracy = (y_test_pred==y_test_batch).float().mean()
        accuracy_list.append(accuracy)

overall_accuracy =sum(accuracy_list)/len(accuracy_list)
print(f"Overall accuracy on the test set: {overall_accuracy:.4f}")

Overall accuracy on the test set: 0.5476