In [1]:
import numpy as np
import pandas as pd
import torch
from sklearn.preprocessing import StandardScaler
from sklearn.model_selection import train_test_split
from sklearn.preprocessing import LabelEncoder

In [2]:
df =pd.read_csv('https://raw.githubusercontent.com/gscdit/Breast-Cancer-Detection/refs/heads/master/data.csv')

In [3]:
df

,id,diagnosis,radius_mean,texture_mean,perimeter_mean,area_mean,smoothness_mean,compactness_mean,concavity_mean,concave points_mean,...,texture_worst,perimeter_worst,area_worst,smoothness_worst,compactness_worst,concavity_worst,concave points_worst,symmetry_worst,fractal_dimension_worst,Unnamed: 32
0,842302,M,17.99,10.38,122.80,1001.0,0.11840,0.27760,0.30010,0.14710,...,17.33,184.60,2019.0,0.16220,0.66560,0.7119,0.2654,0.4601,0.11890,NaN
1,842517,M,20.57,17.77,132.90,1326.0,0.08474,0.07864,0.08690,0.07017,...,23.41,158.80,1956.0,0.12380,0.18660,0.2416,0.1860,0.2750,0.08902,NaN
2,84300903,M,19.69,21.25,130.00,1203.0,0.10960,0.15990,0.19740,0.12790,...,25.53,152.50,1709.0,0.14440,0.42450,0.4504,0.2430,0.3613,0.08758,NaN
3,84348301,M,11.42,20.38,77.58,386.1,0.14250,0.28390,0.24140,0.10520,...,26.50,98.87,567.7,0.20980,0.86630,0.6869,0.2575,0.6638,0.17300,NaN
4,84358402,M,20.29,14.34,135.10,1297.0,0.10030,0.13280,0.19800,0.10430,...,16.67,152.20,1575.0,0.13740,0.20500,0.4000,0.1625,0.2364,0.07678,NaN
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
564,926424,M,21.56,22.39,142.00,1479.0,0.11100,0.11590,0.24390,0.13890,...,26.40,166.10,2027.0,0.14100,0.21130,0.4107,0.2216,0.2060,0.07115,NaN
565,926682,M,20.13,28.25,131.20,1261.0,0.09780,0.10340,0.14400,0.09791,...,38.25,155.00,1731.0,0.11660,0.19220,0.3215,0.1628,0.2572,0.06637,NaN
566,926954,M,16.60,28.08,108.30,858.1,0.08455,0.10230,0.09251,0.05302,...,34.12,126.70,1124.0,0.11390,0.30940,0.3403,0.1418,0.2218,0.07820,NaN
567,927241,M,20.60,29.33,140.10,1265.0,0.11780,0.27700,0.35140,0.15200,...,39.42,184.60,1821.0,0.16500,0.86810,0.9387,0.2650,0.4087,0.12400,NaN
568,92751,B,7.76,24.54,47.92,181.0,0.05263,0.04362,0.00000,0.00000,...,30.37,59.16,268.6,0.08996,0.06444,0.0000,0.0000,0.2871,0.07039,NaN

In [4]:
df.shape

(569, 33)

In [5]:
df.columns

Index(['id', 'diagnosis', 'radius_mean', 'texture_mean', 'perimeter_mean',
       'area_mean', 'smoothness_mean', 'compactness_mean', 'concavity_mean',
       'concave points_mean', 'symmetry_mean', 'fractal_dimension_mean',
       'radius_se', 'texture_se', 'perimeter_se', 'area_se', 'smoothness_se',
       'compactness_se', 'concavity_se', 'concave points_se', 'symmetry_se',
       'fractal_dimension_se', 'radius_worst', 'texture_worst',
       'perimeter_worst', 'area_worst', 'smoothness_worst',
       'compactness_worst', 'concavity_worst', 'concave points_worst',
       'symmetry_worst', 'fractal_dimension_worst', 'Unnamed: 32'],
      dtype='object')

In [6]:
df.drop(columns=['id','Unnamed: 32'],inplace=True)

In [7]:
df.shape

(569, 31)

TRAIN-TEST-SPLIT

In [8]:
x_train,x_test,y_train,y_test = train_test_split(df.drop(columns=['diagnosis']),df['diagnosis'],test_size=0.2,random_state=42)

In [9]:
#SCALING

In [10]:
scaler =StandardScaler()
x_train = scaler.fit_transform(x_train)
x_test = scaler.transform(x_test)

In [11]:
x_train

array([[-1.44075296, -0.43531947, -1.36208497, ...,  0.9320124 ,
         2.09724217,  1.88645014],
       [ 1.97409619,  1.73302577,  2.09167167, ...,  2.6989469 ,
         1.89116053,  2.49783848],
       [-1.39998202, -1.24962228, -1.34520926, ..., -0.97023893,
         0.59760192,  0.0578942 ],
       ...,
       [ 0.04880192, -0.55500086, -0.06512547, ..., -1.23903365,
        -0.70863864, -1.27145475],
       [-0.03896885,  0.10207345, -0.03137406, ...,  1.05001236,
         0.43432185,  1.21336207],
       [-0.54860557,  0.31327591, -0.60350155, ..., -0.61102866,
        -0.3345212 , -0.84628745]])

In [12]:
y_train

68     B
181    M
63     B
248    B
60     B
      ..
71     B
106    B
270    B
435    M
102    B
Name: diagnosis, Length: 455, dtype: object

In [13]:
lb =LabelEncoder()
y_train = lb.fit_transform(y_train)
y_test = lb.transform(y_test)

In [14]:
x_train_tensor =torch.from_numpy(x_train.astype(np.float32))
x_test_tensor =torch.from_numpy(x_test.astype(np.float32))
y_train_tensor =torch.from_numpy(y_train.astype(np.float32))
y_test_tensor =torch.from_numpy(y_test.astype(np.float32))

In [15]:
x_train_tensor.shape

torch.Size([455, 30])

#defining the model

In [21]:
import torch

class MysimpleNN:
    def __init__(self, X):
        self.weights = torch.rand(X.shape[1], 1, requires_grad=True)
        self.bias = torch.rand(1, requires_grad=True)

    def forward(self, X):
        z = torch.matmul(X, self.weights) + self.bias
        y_pred = torch.sigmoid(z)
        return y_pred

    def loss_function(self, y_pred, y):
        epsilon = 1e-7
        y_pred = torch.clamp(y_pred, epsilon, 1 - epsilon)

        # Binary Cross Entropy Loss
        loss = -(y * torch.log(y_pred) +
                 (1 - y) * torch.log(1 - y_pred)).mean()

        return loss

In [47]:
#important parameters
learning_rate =0.1
epochs=56

Training pipeline

In [48]:
model = MysimpleNN(x_train_tensor)


for epoch in range(epochs):

    # Forward pass
    y_pred = model.forward(x_train_tensor)

    # Compute loss
    loss = model.loss_function(y_pred, y_train_tensor)

    # Backward pass
    loss.backward()

    # Update parameters
    with torch.no_grad():
        model.weights -= learning_rate * model.weights.grad
        model.bias -= learning_rate * model.bias.grad

    # Zero gradients
    model.weights.grad.zero_()
    model.bias.grad.zero_()

    print(f"Loss after epoch {epoch+1}: {loss.item():.4f}")

Loss after epoch 1: 4.2306
Loss after epoch 2: 4.1229
Loss after epoch 3: 4.0121
Loss after epoch 4: 3.8985
Loss after epoch 5: 3.7856
Loss after epoch 6: 3.6724
Loss after epoch 7: 3.5559
Loss after epoch 8: 3.4350
Loss after epoch 9: 3.3102
Loss after epoch 10: 3.1782
Loss after epoch 11: 3.0458
Loss after epoch 12: 2.9083
Loss after epoch 13: 2.7620
Loss after epoch 14: 2.6125
Loss after epoch 15: 2.4604
Loss after epoch 16: 2.3088
Loss after epoch 17: 2.1599
Loss after epoch 18: 2.0090
Loss after epoch 19: 1.8634
Loss after epoch 20: 1.7238
Loss after epoch 21: 1.5915
Loss after epoch 22: 1.4672
Loss after epoch 23: 1.3561
Loss after epoch 24: 1.2591
Loss after epoch 25: 1.1769
Loss after epoch 26: 1.1089
Loss after epoch 27: 1.0541
Loss after epoch 28: 1.0108
Loss after epoch 29: 0.9770
Loss after epoch 30: 0.9506
Loss after epoch 31: 0.9295
Loss after epoch 32: 0.9121
Loss after epoch 33: 0.8973
Loss after epoch 34: 0.8842
Loss after epoch 35: 0.8724
Loss after epoch 36: 0.8616
Loss after epoch 37: 0.8515
Loss after epoch 38: 0.8420
Loss after epoch 39: 0.8331
Loss after epoch 40: 0.8247
Loss after epoch 41: 0.8167
Loss after epoch 42: 0.8092
Loss after epoch 43: 0.8021
Loss after epoch 44: 0.7953
Loss after epoch 45: 0.7890
Loss after epoch 46: 0.7829
Loss after epoch 47: 0.7772
Loss after epoch 48: 0.7719
Loss after epoch 49: 0.7668
Loss after epoch 50: 0.7620
Loss after epoch 51: 0.7574
Loss after epoch 52: 0.7531
Loss after epoch 53: 0.7490
Loss after epoch 54: 0.7452
Loss after epoch 55: 0.7415
Loss after epoch 56: 0.7381

In [49]:
model.weights

tensor([[ 0.4207],
        [ 0.3559],
        [-0.1518],
        [ 0.1665],
        [ 0.2029],
        [-0.0046],
        [ 0.1458],
        [-0.4884],
        [-0.2337],
        [ 0.0932],
        [-0.3832],
        [ 0.3774],
        [ 0.2067],
        [-0.1786],
        [ 0.3353],
        [-0.2877],
        [-0.1591],
        [ 0.2105],
        [-0.2719],
        [ 0.3419],
        [ 0.2037],
        [-0.4464],
        [-0.0594],
        [ 0.3167],
        [-0.0711],
        [-0.2318],
        [ 0.1599],
        [-0.2690],
        [ 0.3986],
        [ 0.0828]], requires_grad=True)

In [50]:
model.bias

tensor([0.0681], requires_grad=True)

#evaluation

In [59]:
with torch.no_grad():
    y_pred = model.forward(x_test_tensor)
    y_pred_class = (y_pred > 0.80).float()
    print("Accuracy:", (y_pred_class == y_test_tensor).float().mean().item())

Accuracy: 0.6163434982299805